version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/home/user/app
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:7860/api
    depends_on:
      - backend
    restart: always
